apiVersion: v1
kind: ConfigMap
metadata:
  name: shlink-config
data:
  DEFAULT_DOMAIN: link.ieeetamu.org
  IS_HTTPS_ENABLED: "true"
  DB_DRIVER: mariadb
  DB_NAME: shlink
  DB_USER: shlink
  DB_HOST: mariadb-primary.mariadb.svc
  # IEEE TAMU logo in center
  DEFAULT_QR_CODE_LOGO_URL: https://traefik-helper.ieeetamu.org/web-app-manifest-512x512.png
  # Medium error correction to help with logo in the middle
  DEFAULT_QR_CODE_ERROR_CORRECTION: M
