apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
data:
  DOMAIN: https://vault.ieeetamu.org
  DB_NAME: vaultwarden
  DB_PORT: "3306"
  DB_HOST: mariadb-primary.mariadb.svc
  DB_USER: vaultwarden
  SIGNUPS_ALLOWED: "false"
