apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`docs.ieeetamu.org`)
      kind: Rule
      services:
        - name: docs
          port: 80
