apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
resources:
  - mariadb-backup-cf.yaml
  - mariadb-grafana-dashboard.yaml
  # used a ton of space and when trying to enable replication,
  # things were not working (DBs would come up but then replication would timeout)
  # and controller would show as Role: "Unknown" for all pods.
  # - mariadb-physicalbackup-cf.yaml
  - mariadb-namespace.yaml
  - mariadb.yaml
