apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:TOapWGP6RL4QaA==,iv:80JaipdqVL0DjE0TsH9qOBbm2eZHA9zhsUOlaErcmZ4=,tag:F83Xx5UJ5sF95dGqVRubxw==,type:str]
  password: ENC[AES256_GCM,data:4T2Zz/FuSLUBenjoAtPQQg==,iv:ZzfArMLwYcjQCBPS9HWLPzuyISJ5gOFculbmgDsMqr0=,tag:Wtp2r9yHGZmDTN2Aq7z10Q==,type:str]
sops:
  lastmodified: "2026-01-12T00:07:33Z"
  mac: ENC[AES256_GCM,data:z4KUt9kdCiJVpQPUkmdj9i5o9YR/UF2isBWMvU4qkwLCpOLswpRhTk8FC24vhT6BhDs+atC0XQnBRjEX53c88c1Se5zOGNyf3Z1gTkmwFMJaED9dBse4KF/sO58DKbnCdd4M2zmFcKqB3ftZG/PKt4HhGOEY5mJGEqOdnDEkLeE=,iv:/1Kz3bjRy28Crb12kfEjwPdHm03+0LTfGMAiqjzcqSg=,tag:CNWuajXkjsmEfmzD4fyC/Q==,type:str]
  pgp:
    - created_at: "2026-01-12T00:03:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//XnxMcPpLnq00QxQPDN8m9lyqVmQ5WTn21uk7TK8rTngx
        lredPCpX8VVCKHm5tsOIHwZlEBQ0lA+allc6A7aHEtvfWJlh5vNvExiD8g6fog6y
        qrYSPQ9b39EZk8ycIxyj/Rq5VRMXwI4NEK8qT8iDFx6H1QKg1eHTmeUMcPp6cC1P
        PKGpVo4OXyZQMp30V9ob+27lYfTbpzboYYHH/Ny5+FyXr/li2Ev00WETPLzK82nZ
        a12JhDiiJhT6tLdaLnbCEy4vmMY5NImwLFQ1P7tuHzHxgRDo7P2+ziTRZ2YyPYZs
        o9L1nVCAhqZ9T3gW2jyh811EOZZIc53RyWp7SBMgqntSVom29pKLD/y3+Wh0tkMA
        JIszl5KMcduyoqftWuisBwWQYBn/j8NlkqrIeh/PJaSoga5BJs82G9/swOr0DVqs
        m2s7gEi83jBoTK8ZOA7LbOV9VZ+sm0ar1dquxbbqYDl5PcQQ9iwDXYU5xKmzX5kU
        HDkdsmiTvvTlw/XX7kGlTLRKrocsKTsJOUO4MK87LGxSHDwYsSbNdMvlScUEzb5S
        Yjf/9izc/qCwDCDfK3k9JF/3zWQakRPCpGQdHQy1eQKTBJAF0Omm71kj0WkfNCSC
        vhyKwEhuRWJ7h3cMO5xLGtB4jllW++Nbw39oUF16pI2E6jg/CrYVzmYKdOzCrxzS
        XgEIJ787/16rtMJbm273vgGnpGHD1W+516f6JNTwRqyokptQmhbluN/hj9QRN8G2
        yMcKGEyH5lBWdMc3BY20fzSKkhb31DZ/Jf487PQy13fbJS7IXjqHX8X/xXF0dYc=
        =6+xq
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-01-12T00:03:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAzbESGeu5SzSLlxGfj2PknNMHPqTgBzHXxgnRqaRSe0+x
        1gJyrk623RjTUkfEGekZjYil/fEVaud0F3dQ//PdruR5CJA/8GPiBj5LhRbrjINX
        KtD0hkm0v2MeVACMz/c4Vqa/8qO/C6pROIMAMfrJ0/D7wycuZXVHojIv1Qt3aTB5
        1iaWemvJI24dCCTGU63DWJ0nGG/HSdSm63fHlzoLZeb7yJnVkqPZft4QpiTEZM6k
        OQNI6erabzLGLg6IlkoGh36CROi4NofKz1VCTEqr4FR3F7cXacYHTmbd4jNGmUvk
        9xMPg86FlcKbGILnkGcySQNMrLx3yFlVYWiCcaT3l0i8vlBWjxBoXqLCQxp4qPbL
        7Iap6W5MWvgKpL9xFAazN1NiN3MkeowajYx1S9+6I/e5wZ1LCo8N+ciERnTdlwC8
        RY2H2MGwsECORnvDuM7d+QsD3ZhkDr/e1FTmrJUxtBlWiPS+Bu6m0elOY4BzESoB
        WJvzXqVrGD3nrwJIo7bHx9ohpaYywXXOzGXD4v5J80MOrbt4hlEnQHJgnx6Nv4HJ
        O9Z3SLyBOREZd9HiVDfo0WqmYCHkHJ/Z6xl6dOn8xVm2e1ZhYJIrNK/EkIjQrMWE
        Yg0CJgm7TMtt8JfxvttOnrAsnoNeguy4RpXK94UFhZnh2cQhzPVghcPeA1FGaAPS
        XgHsFd0ee8VbPpw/jUKizNNts++7h3ODFsCu0xY4WxQUIOy756yTRud5qoCoFfs0
        /giar4NIgHJ1GvDS6cfvguSChM0oqI/+XafXLrKH5aKOBX18yE8n/PASqictg9Y=
        =Q81A
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
